#!/usr/bin/env python3
"""
Generates cross-cutting/governance-and-security-index.md from every
domain's 06-policies.md, 07-access-rules.md, and 09-risk-tiers.md, plus
the cross-cutting registries those domains extend.

Governance and Security are not rows in this framework's domain axis —
they are cross-cutting concerns expressed through those three columns at
every domain (00-framework/domain-axis-definition.md). This is an index
of links + item titles, not a duplication of rule text, same principle
glossary-master.md follows for Definitions.

Run from the repo root: python3 <path-to-this-script>
"""
import re
import datetime
import pathlib

ROOT = pathlib.Path(".")

DOMAINS = [
    ("01-infrastructure", "Infrastructure"),
    ("02-networking", "Networking"),
    ("03-system-architecture", "System Architecture"),
    ("04-data-platform", "Data Platform"),
    ("05-data-metadata", "Data/Metadata"),
    ("06-bi-reporting", "Business Intelligence / Reporting"),
    ("07-workflow-process", "Workflow/Process"),
    ("08-harness", "Harness"),
]

ITEM_RE = re.compile(r'^### ([A-Za-z]+-[0-9]+) — (.+?)\s*$', re.M)
FACTOR_ROW_RE = re.compile(r'^\| ([^|]+?) \|', re.M)


def extract_items(path):
    if not path.exists():
        return []
    text = path.read_text(encoding="utf-8")
    return ITEM_RE.findall(text)


def extract_risk_factors(path):
    if not path.exists():
        return []
    text = path.read_text(encoding="utf-8")
    # Find the Determining Factors section, then the first markdown table
    # within it (may be preceded by a paragraph, not immediately after
    # the heading).
    section_m = re.search(r'## Determining Factors[^\n]*\n(.*?)(?=\n## |\Z)', text, re.S)
    if not section_m:
        return []
    section = section_m.group(1)
    table_m = re.search(r'^\|.*Factor.*\n\|[-\s|]+\n((?:\|.*\n)+)', section, re.M)
    if not table_m:
        return []
    rows = table_m.group(1)
    factors = []
    for line in rows.splitlines():
        cell = FACTOR_ROW_RE.match(line)
        if cell:
            factors.append(cell.group(1).strip())
    return factors


def render():
    today = datetime.date.today().isoformat()
    lines = []
    lines.append("# Governance & Security Index (GENERATED)")
    lines.append("")
    lines.append("Status: Generated")
    lines.append(f"Last updated: {today}")
    lines.append("Generated by: 00-framework/scripts/generate_governance_security_index.py")
    lines.append("")
    lines.append(
        "This file is derived from every domain's 06-policies.md, "
        "07-access-rules.md, and 09-risk-tiers.md files, plus the "
        "cross-cutting registries (cross-cutting/policies.md, "
        "access-rules.md, procedures.md, risk-tiers.md) those domains "
        "extend. Governance and Security are not rows in this framework "
        "— they are cross-cutting concerns expressed through those "
        "columns at every domain. This is an index of item IDs, titles, "
        "and links, not a duplication of rule text — open the linked "
        "file for the full rule, rationale, and enforcement detail. Do "
        "not edit this file directly; regenerate with "
        "00-framework/scripts/generate_governance_security_index.py "
        "whenever any domain's Policies, Access Rules, or Risk Tiers "
        "column changes."
    )
    lines.append("")
    lines.append("---")
    lines.append("")

    # Cross-cutting baseline first
    lines.append("## Cross-Cutting Baseline (applies to every domain unless noted)")
    lines.append("")
    cc_sources = [
        ("cross-cutting/policies.md", "Policies"),
        ("cross-cutting/access-rules.md", "Access Rules"),
        ("cross-cutting/procedures.md", "Procedures"),
    ]
    for path_str, label in cc_sources:
        path = ROOT / path_str
        items = extract_items(path)
        lines.append(f"**{label}** ([{path_str}]({path_str})):")
        for item_id, title in items:
            lines.append(f"- {item_id} — {title}")
        lines.append("")
    risk_path = ROOT / "cross-cutting/risk-tiers.md"
    if risk_path.exists():
        lines.append(f"**Risk Scale:** [cross-cutting/risk-tiers.md](cross-cutting/risk-tiers.md) "
                      f"(FIPS 199-aligned Low/Moderate/High — every domain's Risk Tiers column "
                      f"extends this scale rather than defining its own)")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("## Per-Domain Summary")
    lines.append("")

    total_pol = 0
    total_ar = 0
    for d, name in DOMAINS:
        pol_path = ROOT / d / "06-policies.md"
        ar_path = ROOT / d / "07-access-rules.md"
        risk_path = ROOT / d / "09-risk-tiers.md"

        policies = extract_items(pol_path)
        access_rules = extract_items(ar_path)
        factors = extract_risk_factors(risk_path)
        total_pol += len(policies)
        total_ar += len(access_rules)

        lines.append(f"### {name}")
        lines.append("")
        lines.append(f"**Policies** ({len(policies)}) — [{d}/06-policies.md]({d}/06-policies.md):")
        for item_id, title in policies:
            anchor = item_id.lower().replace(' ', '-')
            lines.append(f"- {item_id} — {title}")
        lines.append("")
        lines.append(f"**Access Rules** ({len(access_rules)}) — [{d}/07-access-rules.md]({d}/07-access-rules.md):")
        for item_id, title in access_rules:
            lines.append(f"- {item_id} — {title}")
        lines.append("")
        lines.append(f"**Risk Tier Determining Factors** — [{d}/09-risk-tiers.md]({d}/09-risk-tiers.md):")
        if factors:
            lines.append(", ".join(factors))
        else:
            lines.append("(none extracted)")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(f"**Totals:** {total_pol} domain-specific policies, {total_ar} domain-specific access rules, "
                  f"across {len(DOMAINS)} domains, all extending the same cross-cutting baseline above.")
    lines.append("")
    lines.append("**Quality bar check (00-framework/quality-bar.md):**")
    lines.append("- [x] Simple — one generated index, cross-cutting baseline first, then per-domain")
    lines.append("- [x] Modular — never duplicates rule text, only IDs/titles/links")
    lines.append("- [x] Easy to update — regenerate the script's output, no hand edits")
    lines.append("- [x] Easy to maintain — single source of truth per rule enforced upstream in each domain's own columns")
    lines.append("- [x] Easy to replace — plain markdown, no tooling dependency")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    out = render()
    out_path = ROOT / "cross-cutting/governance-and-security-index.md"
    out_path.write_text(out, encoding="utf-8")
    print(f"wrote {out_path}")
