#!/usr/bin/env python3
"""
Generates 00-framework/ai-resolved-glossary.md: the fully flattened,
self-contained version of every term across the framework, with every
`extends` child's delta merged into its parent's full text and a
provenance note on which part came from where.

Per 00-framework/term-linking-convention.md's "Authoring format vs.
AI-consumption format" section — this is the artifact an AI/harness/
retrieval system should be pointed at, never the raw source files with
unresolved `extends`/reference-stub links.

Run from the repo root: python3 <path-to-this-script>
"""
import re
import datetime
import pathlib

ROOT = pathlib.Path(".")

SOURCES = [
    ("01-infrastructure/01-definitions.md", "Infrastructure", "infra"),
    ("02-networking/01-definitions.md", "Networking", "net"),
    ("03-system-architecture/01-definitions.md", "System Architecture", "sysarch"),
    ("04-data-platform/01-definitions.md", "Data Platform", "dp"),
    ("05-data-metadata/01-definitions.md", "Data/Metadata", "data"),
    ("06-bi-reporting/01-definitions.md", "Business Intelligence / Reporting", "bi"),
    ("07-workflow-process/01-definitions.md", "Workflow/Process", "wf"),
    ("08-harness/01-definitions.md", "Harness", "harness"),
    ("engagements/01-definitions.md", "Engagements", "eng"),
    ("cross-cutting/roles-and-departments/01-definitions.md", "Cross-Cutting: Roles & Departments", "ccrole/ccdept/ccgov/ccorg"),
    ("cross-cutting/sandbox-activation.md", "Cross-Cutting: Sandbox", "cc"),
]

# Matches a term header, capturing everything up to (but not including)
# the next '### ', the next line starting with '#' at any level, or a
# line that is exactly '---'.
TERM_BLOCK_RE = re.compile(
    r'^### (?P<name>.+?) \{#(?P<anchor>[a-z0-9-]+)\}\n(?P<body>.*?)(?=\n### |\n## |\n---|\Z)',
    re.M | re.S,
)

EXTENDS_RE = re.compile(r'^Extends:\s*([a-z0-9-]+)\s*$', re.M)


def parse_terms(path):
    text = (ROOT / path).read_text(encoding="utf-8")
    terms = {}
    for m in TERM_BLOCK_RE.finditer(text):
        anchor = m.group("anchor")
        terms[anchor] = {
            "name": m.group("name").strip(),
            "anchor": anchor,
            "body": m.group("body").strip(),
            "path": path,
        }
    return terms


def collect_all():
    all_terms = {}  # anchor -> term dict, with source domain name attached
    by_domain = []
    for path, domain_name, prefix in SOURCES:
        terms = parse_terms(path)
        for t in terms.values():
            t["domain"] = domain_name
        all_terms.update(terms)
        by_domain.append((domain_name, path, list(terms.values())))
    return all_terms, by_domain


def render_term(t, all_terms):
    lines = []
    lines.append(f"### {t['name']} {{#{t['anchor']}}}")
    lines.append(f"*Source file: {t['path']}*")
    lines.append("")

    m = EXTENDS_RE.search(t["body"])
    if m:
        parent_anchor = m.group(1)
        parent = all_terms.get(parent_anchor)
        if parent:
            # Strip the "Extends: ..." and "Adds: " lines from the child body,
            # keep everything after "Adds:" as the delta text.
            delta = t["body"]
            delta = EXTENDS_RE.sub("", delta).strip()
            delta = re.sub(r'^Adds:\s*', '', delta, flags=re.M).strip()
            lines.append(
                f"**[Flattened — extends `{parent_anchor}`]**"
            )
            lines.append("")
            lines.append(f"**Base definition** (from {parent['domain']}, "
                          f"`{parent['anchor']}`):")
            lines.append("")
            lines.append(parent["body"])
            lines.append("")
            lines.append(f"**Extension** (added by {t['domain']}, "
                          f"`{t['anchor']}`):")
            lines.append("")
            lines.append(delta)
        else:
            lines.append(t["body"])
    else:
        lines.append(t["body"])

    lines.append("")
    return "\n".join(lines)


def render(all_terms, by_domain):
    today = datetime.date.today().isoformat()
    extends_count = sum(1 for t in all_terms.values() if EXTENDS_RE.search(t["body"]))
    lines = []
    lines.append("# AI-Resolved Glossary (GENERATED)")
    lines.append("")
    lines.append("Status: Generated")
    lines.append(f"Last updated: {today}")
    lines.append("Generated by: 00-framework/scripts/generate_ai_resolved_glossary.py")
    lines.append(f"Term count: {len(all_terms)} ({extends_count} flattened via `extends`)")
    lines.append("")
    lines.append(
        "This is the AI/harness/retrieval-consumption-optimized sibling of "
        "00-framework/glossary-master.md. Every term's full definition text "
        "is included here, self-contained — no unresolved cross-file "
        "`extends` hop required. Reference-stub mentions (\"owned "
        "elsewhere\") are left as-is, since a reference stub already "
        "names its owning file directly rather than requiring resolution. "
        "Do not edit directly; regenerate with "
        "00-framework/scripts/generate_ai_resolved_glossary.py whenever "
        "any domain's Definitions column changes."
    )
    lines.append("")
    lines.append(
        "**Provenance convention:** a flattened (`extends`) entry is "
        "marked explicitly, with its base definition and extension each "
        "labeled by owning domain and anchor, so a consumer can always "
        "tell which part came from where. Every other entry is a direct, "
        "unmodified copy of its single owning file's text."
    )
    lines.append("")
    lines.append("---")
    lines.append("")
    for domain_name, path, terms in by_domain:
        terms_sorted = sorted(terms, key=lambda t: t["name"].lower())
        lines.append(f"## {domain_name} ({len(terms_sorted)} terms)")
        lines.append("")
        for t in terms_sorted:
            lines.append(render_term(t, all_terms))
        lines.append("---")
        lines.append("")
    lines.append("**Quality bar check (00-framework/quality-bar.md):**")
    lines.append("- [x] Simple — one generated file, grouped by owning domain, mirrors glossary-master.md's structure")
    lines.append("- [x] Modular — flattening logic isolated to the one genuine `extends` case; every other term passes through unmodified")
    lines.append("- [x] Easy to update — regenerate the script's output, no hand edits")
    lines.append("- [x] Easy to maintain — single source of truth (the domain Definitions files) still enforced upstream; this is a derived view, not a second copy to keep in sync by hand")
    lines.append("- [x] Easy to replace — plain markdown, no tooling dependency; regeneration script is ~150 lines of stdlib-only Python")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    all_terms, by_domain = collect_all()
    out = render(all_terms, by_domain)
    out_path = ROOT / "00-framework/ai-resolved-glossary.md"
    out_path.write_text(out, encoding="utf-8")
    print(f"wrote {out_path} ({len(all_terms)} terms)")
