#!/usr/bin/env python3
"""
Generates 00-framework/glossary-master.md from every domain's and
cross-cutting registry's 01-definitions.md (or equivalent) file.

Scans for `### Term Name {#anchor}` headers only. Never copies definition
text — glossary-master.md is an index of links back to each term's single
owning file, per 00-framework/term-linking-convention.md.

Run from the repo root: python3 <path-to-this-script>
"""
import re
import datetime
import pathlib

ROOT = pathlib.Path(".")

# (source file, display name, relative link prefix)
SOURCES = [
    ("01-infrastructure/01-definitions.md", "Infrastructure"),
    ("02-networking/01-definitions.md", "Networking"),
    ("03-system-architecture/01-definitions.md", "System Architecture"),
    ("04-data-platform/01-definitions.md", "Data Platform"),
    ("05-data-metadata/01-definitions.md", "Data/Metadata"),
    ("06-bi-reporting/01-definitions.md", "Business Intelligence / Reporting"),
    ("07-workflow-process/01-definitions.md", "Workflow/Process"),
    ("08-harness/01-definitions.md", "Harness"),
    ("engagements/01-definitions.md", "Engagements"),
    ("cross-cutting/roles-and-departments/01-definitions.md", "Cross-Cutting: Roles & Departments"),
    ("cross-cutting/sandbox-activation.md", "Cross-Cutting: Sandbox"),
]

TERM_RE = re.compile(r'^### (.+?) \{#([a-z0-9-]+)\}', re.M)


def collect():
    sections = []
    total = 0
    for path, name in SOURCES:
        text = (ROOT / path).read_text(encoding="utf-8")
        terms = TERM_RE.findall(text)
        terms_sorted = sorted(terms, key=lambda t: t[0].lower())
        sections.append((name, path, terms_sorted))
        total += len(terms_sorted)
    return sections, total


def render(sections, total):
    today = datetime.date.today().isoformat()
    lines = []
    lines.append("# Unified Glossary (GENERATED)")
    lines.append("")
    lines.append(f"Status: Generated")
    lines.append(f"Last updated: {today}")
    lines.append(f"Generated by: 00-framework/scripts/generate_glossary.py")
    lines.append(f"Term count: {total}")
    lines.append("")
    lines.append(
        "This file is derived from every domain's and cross-cutting "
        "registry's 01-definitions.md (or equivalent) file. It is an "
        "index of links back to each term's single owning file — it "
        "never contains copied definition text. Do not edit directly; "
        "regenerate with 00-framework/scripts/generate_glossary.py "
        "whenever a domain's Definitions column changes."
    )
    lines.append("")
    lines.append(
        "For the fully flattened, self-contained version of every term "
        "(parent text merged with every `extends` child's delta), see "
        "00-framework/ai-resolved-glossary.md instead — this index is "
        "for human navigation; that one is for AI/harness consumption."
    )
    lines.append("")
    lines.append("---")
    lines.append("")
    for name, path, terms in sections:
        lines.append(f"## {name} ({len(terms)} terms)")
        lines.append("")
        for term_name, anchor in terms:
            lines.append(f"- [{term_name}](../{path}#{anchor})")
        lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("**Quality bar check (00-framework/quality-bar.md):**")
    lines.append("- [x] Simple — one generated index, grouped by owning domain")
    lines.append("- [x] Modular — never duplicates definition text, only links")
    lines.append("- [x] Easy to update — regenerate the script's output, no hand edits")
    lines.append("- [x] Easy to maintain — single source of truth per term enforced upstream")
    lines.append("- [x] Easy to replace — plain markdown links, no tooling dependency")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    sections, total = collect()
    out = render(sections, total)
    out_path = ROOT / "00-framework/glossary-master.md"
    out_path.write_text(out, encoding="utf-8")
    print(f"wrote {out_path} ({total} terms)")
