#!/usr/bin/env python3
"""
Generates roadmap/roadmap.md from every domain's _status.yaml, in
traversal order (00-framework/traversal-order.md).

Run from the repo root: python3 <path-to-this-script>
"""
import re
import datetime
import pathlib

ROOT = pathlib.Path(".")

# Traversal order (00-framework/traversal-order.md): ascending domain #.
DOMAINS = [
    ("01-infrastructure", "Infrastructure", "Platform Engineering"),
    ("02-networking", "Networking", "Platform Engineering"),
    ("03-system-architecture", "System Architecture", "Application Engineering"),
    ("04-data-platform", "Data Platform", "Data Governance & Engineering"),
    ("05-data-metadata", "Data/Metadata", "Data Governance & Engineering"),
    ("06-bi-reporting", "Business Intelligence / Reporting", "Business Intelligence & Analytics"),
    ("07-workflow-process", "Workflow/Process", "Every department (own instance) - standards owned cross-cutting by DevOps/Release Engineering"),
    ("08-harness", "Harness", "AI/ML Platform"),
]

ENGAGEMENTS_COLS = [
    "00-standards-alignment", "01-definitions", "02-engagement-types",
    "03-project-document-template", "04-task-document-template",
    "05-intake-and-vetting", "06-participants-collaboration-and-channels",
    "07-planning-and-advisory-agents", "08-worked-example", "09-open-decisions",
]

CROSS_CUTTING_PILLARS = [
    ("Governance & Security", "Every domain's 06-policies.md/07-access-rules.md/09-risk-tiers.md extends cross-cutting/policies.md, access-rules.md, procedures.md, risk-tiers.md", "Security & Compliance (cross-cutting reviewer/approver)"),
    ("Roles & Departments", "cross-cutting/roles-and-departments/", "Every department; IT Training & Change Management owns the Training Requirement mechanism cross-cuttingly"),
    ("Sandbox", "cross-cutting/sandbox-activation.md", "Consumed by Workflow/Process and Harness; provisioned like any other resource (CCPROC-1)"),
]

STATUS_ORDER = ["not-started", "draft", "ratified", "deprecated", "superseded"]


def load_status(rel_path):
    text = (ROOT / rel_path).read_text(encoding="utf-8")
    cols = {}
    in_cols = False
    for line in text.splitlines():
        if line.strip() == "columns:":
            in_cols = True
            continue
        if in_cols:
            m = re.match(r'\s+([0-9]{2}-[a-z-]+):\s*(\S+)', line)
            if m:
                cols[m.group(1)] = m.group(2)
    return cols


def render():
    today = datetime.date.today().isoformat()
    lines = []
    lines.append("# Roadmap (GENERATED)")
    lines.append("")
    lines.append("Status: Generated")
    lines.append(f"Last updated: {today}")
    lines.append("Generated by: 00-framework/scripts/generate_roadmap.py")
    lines.append("")
    lines.append(
        "Derived from every domain's _status.yaml, in traversal order "
        "(00-framework/traversal-order.md). Shows sequencing, ownership, "
        "and maturity across the whole framework. Do not edit directly; "
        "regenerate with 00-framework/scripts/generate_roadmap.py "
        "whenever any domain's _status.yaml changes."
    )
    lines.append("")
    lines.append(
        "For the leadership-facing version of this same phase structure, "
        "reframed around risk reduction and pace-of-adoption rather than "
        "definitional detail, see roadmap/buy-in-narrative.md."
    )
    lines.append("")
    lines.append("---")
    lines.append("")

    all_cols = ["00-standards-alignment", "01-definitions", "02-taxonomies",
                "03-ontologies", "04-metadata-standards", "05-conventions",
                "06-policies", "07-access-rules", "08-procedures",
                "09-risk-tiers", "10-tooling"]

    domain_rows = []
    for d, name, owner in DOMAINS:
        cols = load_status(f"{d}/_status.yaml")
        counts = {}
        for s in STATUS_ORDER:
            counts[s] = sum(1 for c in all_cols if cols.get(c) == s)
        domain_rows.append((d, name, owner, counts))

    lines.append("## Phase 0 - Domain Build (Complete)")
    lines.append("")
    lines.append(
        "All 8 domains and all 3 cross-cutting pillars have been built in "
        "traversal order. Every domain's 11 columns are drafted; none are "
        "yet ratified."
    )
    lines.append("")
    lines.append("| # | Domain | Owning Department | Draft | Ratified | Not Started |")
    lines.append("|---|---|---|---|---|---|")
    for i, (d, name, owner, counts) in enumerate(domain_rows, start=1):
        lines.append(f"| {i} | [{name}]({d}/) | {owner} | {counts['draft']}/11 | {counts['ratified']}/11 | {counts['not-started']}/11 |")
    lines.append("")

    lines.append("**Cross-Cutting Pillars:**")
    lines.append("")
    lines.append("| Pillar | Location | Owner |")
    lines.append("|---|---|---|")
    for name, loc, owner in CROSS_CUTTING_PILLARS:
        lines.append(f"| {name} | `{loc}` | {owner} |")
    lines.append("")

    lines.append("**Engagements Area** (new 2026-09-23, not a domain - 00-framework/domain-axis-definition.md):")
    lines.append("")
    eng_cols = load_status("engagements/_status.yaml")
    eng_counts = {}
    for s in STATUS_ORDER:
        eng_counts[s] = sum(1 for c in ENGAGEMENTS_COLS if eng_cols.get(c) == s)
    lines.append("| Area | Location | Draft | Ratified | Not Started |")
    lines.append("|---|---|---|---|---|")
    lines.append(f"| Engagements | [engagements/](engagements/) | {eng_counts['draft']}/{len(ENGAGEMENTS_COLS)} | {eng_counts['ratified']}/{len(ENGAGEMENTS_COLS)} | {eng_counts['not-started']}/{len(ENGAGEMENTS_COLS)} |")
    lines.append("")
    lines.append(
        "Unit-of-work planning layer on top of the domain axis - Engagement "
        "Documents (Project/Task), the Vetting Agent, and the Engagement "
        "Planning Agent. Consumes the Anchor layer (domains above) and "
        "Harness's Agent schema rather than duplicating either. Open "
        "items tracked in engagements/09-open-decisions.md, including the "
        "Skill/Agent Library and Factory process as the natural next "
        "pieces."
    )
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("## Phase 1 - Ratification Review (Next)")
    lines.append("")
    lines.append(
        "Every domain is fully drafted but not yet ratified "
        "(00-framework/quality-bar.md's Status/Ratified fields, tracked "
        "per-file). Ratification is a deliberate, separate step from "
        "drafting - this framework was built with an AI-drafted-then-"
        "human-reviewed workflow throughout "
        "(00-framework/traversal-order.md's Q&A provenance rule), and "
        "every _qa/*.qa.md entry across all 8 domains is currently "
        "logged \"Pending explicit review.\""
    )
    lines.append("")
    lines.append(
        "**Recommended review order:** same traversal order used to "
        "build the framework (Infrastructure through Harness), since "
        "later domains' cross-domain references depend on earlier "
        "domains' anchors already being stable. Cross-cutting pillars "
        "(Governance/Security, Roles & Departments, Sandbox) are "
        "threaded through every domain's Policies/Access Rules/Risk "
        "Tiers columns rather than reviewed as a separate pass."
    )
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Phase 2 - Housekeeping & Tooling (In Progress)")
    lines.append("")
    lines.append("| Item | Status |")
    lines.append("|---|---|")
    lines.append("| `00-framework/glossary-master.md` (unified glossary index) | Generated |")
    lines.append("| `00-framework/ai-resolved-glossary.md` (AI-consumption flattened glossary) | Generated |")
    lines.append("| `cross-cutting/governance-and-security-index.md` (rollup) | Generated |")
    lines.append("| `roadmap/roadmap.md` (this file) | Generated |")
    lines.append("| `roadmap/buy-in-narrative.md` (leadership-facing) | Authored |")
    lines.append("")
    lines.append(
        "All five now have regeneration scripts under "
        "`00-framework/scripts/`, except buy-in-narrative.md, which is "
        "editorial content authored once and updated by hand as the "
        "roadmap's phases change, not mechanically regenerated."
    )
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Phase 3 - Not Yet Designed (Open, per traversal-order.md)")
    lines.append("")
    lines.append(
        "- State/history management for ratified content that changes "
        "later (correction vs. evolution, versioning scheme, "
        "dependent-domain re-validation flags)"
    )
    lines.append(
        "- Migration path from file-based source of truth to a queryable "
        "structured store (e.g. for harness runtime consumption)"
    )
    lines.append("")
    lines.append("**Quality bar check (00-framework/quality-bar.md):**")
    lines.append("- [x] Simple - one generated roadmap, four phases")
    lines.append("- [x] Modular - pulls status from each domain's own _status.yaml, no duplicated maturity tracking")
    lines.append("- [x] Easy to update - regenerate the script's output, no hand edits")
    lines.append("- [x] Easy to maintain - single source of truth per domain's status enforced upstream")
    lines.append("- [x] Easy to replace - plain markdown, no tooling dependency")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    out = render()
    out_path = ROOT / "roadmap/roadmap.md"
    out_path.write_text(out, encoding="utf-8")
    print(f"wrote {out_path}")
